### ISSUE TITLE
ng-speech with Ionic 2

### ISSUE THREAD

**Issue by ghost** [Devniz/ng-speech-recognition#1]
How is possible to make this feature available on AngularJS2 + ionic2?

**Comment by devniz** [comment]
Hi,

I need to refactor the directive to Angular 2 and it should work. You can also do it and send me a pull request.

**Comment by ghost** [comment]
Hi @Devniz, unfortunately, i have no idea how to do that.

Maybe could you give me some guideline?
Or, if you have time, could you refactor the directive to Angular 2 (and ionic2, consequently)?

I need it for a work project.. 👍 
Thank you.

**Comment by ghost** [comment]
@Devniz, have you some news?
