### ISSUE TITLE
Is it usable without Ionic?

### ISSUE THREAD

**Issue by desmeit** [Devniz/ng-speech-recognition#3]
I create a App with Framework7, is it possible to use the Plugin?
And one more question: Is it also working with Cordova and IOS?

**Comment by devniz** [comment]
@desmeit It should work just fine as long as you are using AngularJS 1.x version.

**Comment by desmeit** [comment]
thank you @NizarBsb 
Also for IOS?

**Comment by devniz** [comment]
@desmeit Yes you don't need ionic Framework, this is just an AngularJS directive. It works on Android and iOS, just give it a try and let me know.

**Comment by desmeit** [comment]
perfectly, i will let you know.

**Comment by leshik** [comment]
@NizarBsb
> and iOS

Are you sure? `Google Web Speech API` isn't available in `WKWebView`...

**Comment by devniz** [comment]
> WKWebView

Hi, @leshik Sorry, I'm not so sure I'm following what do you mean by this? This is an AngularJS directive for a hybrid app only working with Android and iOS, this is not a native component.

**Comment by leshik** [comment]
WKWebView is webkit engine on iOS. It doesn’t support chrome’s web speech API. Crosswalk is discontinued 2 years ago. That said, I doubt it will work on iOS.

**Comment by devniz** [comment]
@leshik You are right, I am actually not supporting this project anymore and thank you very much for telling me about crosswalk.

**Comment by devniz** [comment]
@leshik What are you working on? Are you using ionic Framework or simple Cordova app? I am interested to know so maybe I can release something new for iOS using speech-recognition. This repository is deprecated expect if you are working with old legacy AngularJS code.

**Comment by leshik** [comment]
@NizarBsb I'm not using Ionic as our app is React based, so I started with just plain Cordova, then discovered Capacitor by Ionic team (that is framework agnostic). I need some native features for our app (push notifications & speech recognition) that's why I'm looking at this plugin. Now I'm experimenting with https://github.com/pbakondy/cordova-plugin-speechrecognition, seems to be a good fit.

**Comment by devniz** [comment]
@leshik Ok, that's great that you find something which fit your needs. Good luck.
